"""This is the ui object for the popup application form"""

from __future__ import annotations

import traceback
from typing import Self

import discord


class VoteCreation(discord.ui.Modal, title="Staff voting"):
    """The class contianing the modal and all variables for it
    This must be sent as a response to an interaction, cannot be from a prefix command

    Attributes:
        vote_short (discord.TextInput): The title to make the forum thread for the vote
        vote_reason (discord.TextInput): The main body of the vote
    """

    vote_short: discord.TextInput = discord.ui.TextInput(
        label="What are you starting a vote for?",
        style=discord.TextStyle.short,
        required=True,
        max_length=94,
    )
    vote_reason: discord.TextInput = discord.ui.TextInput(
        label="Describe your vote",
        style=discord.TextStyle.paragraph,
        required=True,
        max_length=1500,
    )

    async def on_submit(self: Self, interaction: discord.Interaction) -> None:
        """What happens when the form has been successfully submitted

        Args:
            interaction (discord.Interaction): The interaction that caused the form to be show
        """
        await interaction.response.defer()
        return

    async def on_error(
        self: Self, interaction: discord.Interaction, error: Exception
    ) -> None:
        """What happens if there is an error in the application processing

        Args:
            interaction (discord.Interaction): The interaction that caused the form to be show
            error (Exception): The error generated by the application
        """
        await interaction.response.send_message(
            "Oops! Something went wrong.",
            ephemeral=True,
        )

        # Make sure we know what the error actually is
        traceback.print_exception(type(error), error, error.__traceback__)
