FROM python:3.9-alpine

RUN apk update && \
    apk add --no-cache \
    postgresql-dev \
    gcc \
    musl-dev

WORKDIR /var/TechSupportBot
COPY Pipfile.lock .

RUN pip install pipenv && \
    pipenv requirements --dev > /tmp/requirements.txt && \
    pip install --no-cache-dir -r /tmp/requirements.txt

COPY . .
COPY config.yml techsupport_bot

CMD python3 -u techsupport_bot/main.py