version: '3'

services:

    bot:
        image: rtechsupport/techsupport-bot:dev
        container_name: techsupport_bot
        environment:
            - DEBUG=1
        volumes:
            - ./:/var/TechSupportBot
            # - ../BotLog/src/botlog:/usr/local/lib/python3.9/site-packages/botlog