"""Module for the translate extension for the discord bot."""

from __future__ import annotations

from typing import TYPE_CHECKING, Self

import discord
from core import auxiliary, cogs
from discord import app_commands

if TYPE_CHECKING:
    import bot


async def setup(bot: bot.TechSupportBot) -> None:
    """Loading the Translate plugin into the bot

    Args:
        bot (bot.TechSupportBot): The bot object to register the cogs to
    """
    await bot.add_cog(Translator(bot=bot))


class Translator(cogs.BaseCog):
    """Class to set up the translate extension.

    Attributes:
        API_URL (str): The translated API URL

    """

    API_URL: str = "https://api.mymemory.translated.net/get?q={}&langpair={}|{}"

    @app_commands.command(
        name="translate",
        description="Translates a given input message to another language",
        extras={"module": "translate"},
    )
    async def translate(
        self: Self,
        interaction: discord.Interaction,
        message: str,
        src: str,
        dest: str,
    ) -> None:
        """Translates user input into another language

        Args:
            interaction (discord.Interaction): The interaction generated by running this command
            message (str): The string to translate
            src (str): The language the message is currently in
            dest (str): The target language to translate to
        """
        normalized_message, normalized_src, normalized_dest = (
            normalize_translation_input(message, src, dest)
        )
        invalid_input_message = validate_translation_inputs(
            normalized_message, normalized_src, normalized_dest
        )
        if invalid_input_message:
            await interaction.response.send_message(
                embed=auxiliary.prepare_deny_embed(invalid_input_message)
            )
            return

        url = build_translate_url(
            self.API_URL, normalized_message, normalized_src, normalized_dest
        )
        response = await self.bot.http_functions.http_call(
            "get",
            url,
            use_app_error=True,
        )
        translated = extract_translated_text(response)

        if not translated:
            await interaction.response.send_message(
                embed=auxiliary.prepare_deny_embed(build_translation_failure_message())
            )
            return

        await interaction.response.send_message(
            embed=auxiliary.prepare_confirm_embed(translated)
        )


def normalize_translation_input(
    message: str, src: str, dest: str
) -> tuple[str, str, str]:
    """Normalizes translation command arguments.

    Args:
        message (str): The message to translate
        src (str): The source language code
        dest (str): The destination language code

    Returns:
        tuple[str, str, str]: The normalized message, source, and destination inputs
    """
    normalized_message = message.strip()
    normalized_src = src.strip().lower()
    normalized_dest = dest.strip().lower()

    return normalized_message, normalized_src, normalized_dest


def validate_translation_inputs(message: str, src: str, dest: str) -> str | None:
    """Validates translation inputs and returns a user-facing deny message if invalid.

    Args:
        message (str): The message to translate
        src (str): The source language code
        dest (str): The destination language code

    Returns:
        str | None: Deny message if invalid, otherwise None
    """
    if len(message) == 0:
        return "You need to provide a message to translate"

    if len(src) == 0:
        return "You need to provide a source language code"

    if len(dest) == 0:
        return "You need to provide a destination language code"

    return None


def build_translate_url(
    api_url_template: str, message: str, src: str, dest: str
) -> str:
    """Builds the final translation API URL from normalized input arguments.

    Args:
        api_url_template (str): The API URL template for translation requests
        message (str): The message to translate
        src (str): The source language code
        dest (str): The destination language code

    Returns:
        str: The final URL to call for translation
    """
    final_url = api_url_template.format(message, src, dest)
    return final_url


def extract_translated_text(response: dict) -> str | None:
    """Extracts translated text from translation API responses.

    Args:
        response (dict): The API response payload

    Returns:
        str | None: The translated text if present, otherwise None
    """
    response_data = response.get("responseData")
    if not response_data:
        return None

    translated_text = response_data.get("translatedText")
    if not translated_text:
        return None

    return str(translated_text)


def build_translation_failure_message() -> str:
    """Builds the standard failure message for translation attempts.

    Returns:
        str: A user-facing failure message
    """
    return "I could not translate your message"
