"""Module for the urban dictionary extension for the discord bot."""

from __future__ import annotations

from typing import TYPE_CHECKING, Self

import discord
import ui
from core import auxiliary, cogs, extensionconfig
from discord.ext import commands

if TYPE_CHECKING:
    import bot


async def setup(bot: bot.TechSupportBot) -> None:
    """Loading the Urban plugin into the bot

    Args:
        bot (bot.TechSupportBot): The bot object to register the cogs to
    """
    config = extensionconfig.ExtensionConfig()
    config.add(
        key="max_responses",
        datatype="int",
        title="Max Responses",
        description="The max amount of responses per embed page",
        default=1,
    )

    await bot.add_cog(UrbanDictionary(bot=bot))
    bot.add_extension_config("urban", config)


class UrbanDictionary(cogs.BaseCog):
    """Class for setting up the urban dictionary extension.

    Attrs:
        BASE_URL (str): The base API URL for urban dict
        SEE_MORE_URL (str): The URL to link to search results from the API
        ICON_URL (str): The urban dict icon URL

    """

    BASE_URL = "http://api.urbandictionary.com/v0/define?term="
    SEE_MORE_URL = "https://www.urbandictionary.com/define.php?term="
    ICON_URL = "https://cdn.icon-icons.com/icons2/114/PNG/512/dictionary_19159.png"

    @auxiliary.with_typing
    @commands.command(
        name="urb",
        aliases=["urbandictionary", "urban"],
        brief="Searches Urban Dictionary",
        description="Returns the top Urban Dictionary search result",
        usage="[query]",
    )
    async def urban(self: Self, ctx: commands.Context, *, query: str) -> None:
        """Searches urban dictionary and sends a paginated list of results to the user

        Args:
            ctx (commands.Context): The context generated by running this command
            query (str): The query to urban dictionary
        """
        response = await self.bot.http_functions.http_call(
            "get", f"{self.BASE_URL}{query}"
        )
        definitions = response.get("list")

        config = self.bot.guild_configs[str(ctx.guild.id)]

        if not definitions:
            await auxiliary.send_deny_embed(
                message=f"No results found for: *{query}*", channel=ctx.channel
            )
            return

        query_no_spaces = query.replace(" ", "%20")
        embeds = []
        field_counter = 1
        for index, definition in enumerate(definitions):
            message = (
                definition.get("definition")
                .replace("[", "")
                .replace("]", "")
                .replace("\n", "")
            )
            embed = (
                discord.Embed(
                    title=f"Results for {query}",
                    description=f"{self.SEE_MORE_URL}{query_no_spaces}",
                )
                if field_counter == 1
                else embed
            )
            embed.add_field(
                name=f"{message[:200]}",
                value=definition.get("author", "Author Unknown"),
                inline=False,
            )
            if (
                field_counter == config.extensions.urban.max_responses.value
                or index == len(definitions) - 1
            ):
                embed.set_thumbnail(url=self.ICON_URL)
                embed.color = discord.Color.dark_green()
                embeds.append(embed)
                field_counter = 1
            else:
                field_counter += 1

        await ui.PaginateView().send(ctx.channel, ctx.author, embeds)
