"""Module for the weather extension for the discord bot."""

from __future__ import annotations

from typing import TYPE_CHECKING, Self

import discord
import munch
from core import auxiliary, cogs
from discord import app_commands

if TYPE_CHECKING:
    import bot


async def setup(bot: bot.TechSupportBot) -> None:
    """Loading the Weather plugin into the bot

    Args:
        bot (bot.TechSupportBot): The bot object to register the cogs to

    Raises:
        AttributeError: Raised if an API key is missing to prevent unusable commands from loading
    """

    # Don't load without the API key
    try:
        if not bot.file_config.api.api_keys.open_weather:
            raise AttributeError("Weather was not loaded due to missing API key")
    except AttributeError as exc:
        raise AttributeError("Weather was not loaded due to missing API key") from exc

    await bot.add_cog(Weather(bot=bot))


class Weather(cogs.BaseCog):
    """Class to set up the weather extension for the discord bot."""

    @app_commands.command(
        name="weather",
        description=(
            "Returns the weather for a given area with both Fahrenheit and Celsius"
        ),
        extras={"module": "weather"},
    )
    async def weather(
        self: Self,
        interaction: discord.Interaction,
        city_name: str,
        state_code: str = None,
        country_code: str = None,
    ) -> None:
        """This is the main logic for the weather command. This prepares the API data
        and sends a message to discord

        Args:
            interaction (discord.Interaction): The interaction generated by running this command
            city_name (str): For the API, the name of the city to get weather for
            state_code (str, optional): For the API, if applicable, the state code to search for.
                Defaults to None.
            country_code (str, optional): For the API, if needed you can add a country code to
                search for. Defaults to None.
        """
        query = build_weather_query(city_name, state_code, country_code)
        url = build_weather_url(
            query=query,
            api_key=self.bot.file_config.api.api_keys.open_weather,
        )
        response = await self.bot.http_functions.http_call(
            "get", url, use_app_error=True
        )

        embed = self.generate_embed(munch.munchify(response))
        if not embed:
            await interaction.response.send_message(
                embed=auxiliary.prepare_deny_embed(
                    "I could not find the weather from your search"
                )
            )
            return

        await interaction.response.send_message(embed=embed)

    def generate_embed(self: Self, response: munch.Munch) -> discord.Embed | None:
        """Creates an embed filled with weather data:
        Current Temp
        High temp
        Low temp
        Humidity
        Condition

        Args:
            response (munch.Munch): The response from the API containing the weather data

        Returns:
            discord.Embed | None: Either the formatted embed, or nothing if the API failed
        """
        weather_fields = extract_weather_fields(response)
        if not weather_fields:
            return None

        embed = discord.Embed(title=weather_fields["title"])
        embed.add_field(
            name="Description", value=weather_fields["description"], inline=False
        )
        embed.add_field(name="Temp", value=weather_fields["temp"], inline=False)
        embed.add_field(name="Low", value=weather_fields["low"])
        embed.add_field(name="High", value=weather_fields["high"])
        embed.add_field(name="Humidity", value=weather_fields["humidity"])
        embed.set_thumbnail(
            url=(
                "https://www.iconarchive.com/download/i76758"
                "/pixelkit/flat-jewels/Weather.512.png"
            )
        )
        embed.color = discord.Color.blurple()

        return embed


def build_weather_query(
    city_name: str, state_code: str | None = None, country_code: str | None = None
) -> str:
    """Builds a weather search query from city/state/country parts.

    Args:
        city_name (str): The city or town name
        state_code (str | None, optional): The state code. Defaults to None.
        country_code (str | None, optional): The country code. Defaults to None.

    Returns:
        str: The cleaned search query used for OpenWeather q parameter
    """
    raw_parts = [city_name, state_code, country_code]
    cleaned_parts = []
    for part in raw_parts:
        if part is None:
            continue
        cleaned_part = str(part).strip()
        if len(cleaned_part) == 0:
            continue
        cleaned_parts.append(cleaned_part)

    return ",".join(cleaned_parts)


def build_weather_url(query: str, api_key: str, units: str = "imperial") -> str:
    """Builds an OpenWeather API URL.

    Args:
        query (str): The q query value for OpenWeather
        api_key (str): The OpenWeather API key
        units (str, optional): OpenWeather units value. Defaults to "imperial".

    Returns:
        str: The full API URL
    """
    base_url = "http://api.openweathermap.org/data/2.5/weather"
    return f"{base_url}?q={query}&units={units}&appid={api_key}"


def fahrenheit_to_celsius(temperature_f: float) -> float:
    """Converts Fahrenheit to Celsius.

    Args:
        temperature_f (float): Temperature in Fahrenheit

    Returns:
        float: Temperature in Celsius
    """
    return (temperature_f - 32) * (5 / 9)


def format_dual_temperature(temperature_f: float) -> str:
    """Formats a temperature in Fahrenheit and Celsius.

    Args:
        temperature_f (float): Temperature in Fahrenheit

    Returns:
        str: Formatted output in `F (C)` shape
    """
    celsius = fahrenheit_to_celsius(float(temperature_f))
    return f"{int(round(temperature_f))}°F ({int(round(celsius))}°C)"


def extract_weather_fields(response: munch.Munch) -> dict[str, str] | None:
    """Extracts weather display fields from API response data.

    Args:
        response (munch.Munch): The OpenWeather response payload

    Returns:
        dict[str, str] | None: Render-ready weather fields, or None if payload is invalid
    """
    try:
        title = f"Weather for {response.name} ({response.sys.country})"
        descriptions = ", ".join(weather.description for weather in response.weather)

        current = format_dual_temperature(float(response.main.temp))
        feels_like = format_dual_temperature(float(response.main.feels_like))
        low = format_dual_temperature(float(response.main.temp_min))
        high = format_dual_temperature(float(response.main.temp_max))
        humidity = f"{int(response.main.humidity)} %"
    except (AttributeError, KeyError, TypeError, ValueError):
        return None

    return {
        "title": title,
        "description": descriptions,
        "temp": f"{current} (feels like {feels_like})",
        "low": low,
        "high": high,
        "humidity": humidity,
    }
