name: flake8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install pip==$(sed -nE 's/pip = "==(.*)"/\1/p' Pipfile)
        pip install pipenv==$(sed -nE 's/pipenv = "==(.*)"/\1/p' Pipfile)
        pipenv install --system
    - name: Analysing the code with flake8
      run: |
        flake8 $(git rev-parse --show-toplevel)
